// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.0
// source: fl_status/fl_status.proto

package fl_status

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// stages of fl round
type Stages int32

const (
	Stages_SELECTION     Stages = 0
	Stages_CONFIGURATION Stages = 1
	Stages_REPORTING     Stages = 2
	Stages_COMPLETED     Stages = 3
)

// Enum value maps for Stages.
var (
	Stages_name = map[int32]string{
		0: "SELECTION",
		1: "CONFIGURATION",
		2: "REPORTING",
		3: "COMPLETED",
	}
	Stages_value = map[string]int32{
		"SELECTION":     0,
		"CONFIGURATION": 1,
		"REPORTING":     2,
		"COMPLETED":     3,
	}
)

func (x Stages) Enum() *Stages {
	p := new(Stages)
	*p = x
	return p
}

func (x Stages) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Stages) Descriptor() protoreflect.EnumDescriptor {
	return file_fl_status_fl_status_proto_enumTypes[0].Descriptor()
}

func (Stages) Type() protoreflect.EnumType {
	return &file_fl_status_fl_status_proto_enumTypes[0]
}

func (x Stages) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Stages.Descriptor instead.
func (Stages) EnumDescriptor() ([]byte, []int) {
	return file_fl_status_fl_status_proto_rawDescGZIP(), []int{0}
}

// FLRoundStatus
type FLRoundStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stage   Stages `protobuf:"varint,1,opt,name=stage,proto3,enum=Stages" json:"stage,omitempty"`
	RoundNo uint32 `protobuf:"varint,2,opt,name=roundNo,proto3" json:"roundNo,omitempty"`
}

func (x *FLRoundStatus) Reset() {
	*x = FLRoundStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fl_status_fl_status_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FLRoundStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FLRoundStatus) ProtoMessage() {}

func (x *FLRoundStatus) ProtoReflect() protoreflect.Message {
	mi := &file_fl_status_fl_status_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FLRoundStatus.ProtoReflect.Descriptor instead.
func (*FLRoundStatus) Descriptor() ([]byte, []int) {
	return file_fl_status_fl_status_proto_rawDescGZIP(), []int{0}
}

func (x *FLRoundStatus) GetStage() Stages {
	if x != nil {
		return x.Stage
	}
	return Stages_SELECTION
}

func (x *FLRoundStatus) GetRoundNo() uint32 {
	if x != nil {
		return x.RoundNo
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fl_status_fl_status_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_fl_status_fl_status_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_fl_status_fl_status_proto_rawDescGZIP(), []int{1}
}

var File_fl_status_fl_status_proto protoreflect.FileDescriptor

var file_fl_status_fl_status_proto_rawDesc = []byte{
	0x0a, 0x19, 0x66, 0x6c, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2f, 0x66, 0x6c, 0x5f, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x48, 0x0a, 0x0d, 0x46,
	0x4c, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1d, 0x0a, 0x05,
	0x73, 0x74, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x07, 0x2e, 0x53, 0x74,
	0x61, 0x67, 0x65, 0x73, 0x52, 0x05, 0x73, 0x74, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x72,
	0x6f, 0x75, 0x6e, 0x64, 0x4e, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x72, 0x6f,
	0x75, 0x6e, 0x64, 0x4e, 0x6f, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x2a, 0x48,
	0x0a, 0x06, 0x53, 0x74, 0x61, 0x67, 0x65, 0x73, 0x12, 0x0d, 0x0a, 0x09, 0x53, 0x45, 0x4c, 0x45,
	0x43, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x43, 0x4f, 0x4e, 0x46, 0x49,
	0x47, 0x55, 0x52, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x52, 0x45,
	0x50, 0x4f, 0x52, 0x54, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x4f, 0x4d,
	0x50, 0x4c, 0x45, 0x54, 0x45, 0x44, 0x10, 0x03, 0x32, 0x36, 0x0a, 0x08, 0x46, 0x6c, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x2a, 0x0a, 0x0e, 0x67, 0x65, 0x74, 0x52, 0x6f, 0x75, 0x6e, 0x64,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0e,
	0x2e, 0x46, 0x4c, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x00,
	0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2f, 0x66, 0x6c, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_fl_status_fl_status_proto_rawDescOnce sync.Once
	file_fl_status_fl_status_proto_rawDescData = file_fl_status_fl_status_proto_rawDesc
)

func file_fl_status_fl_status_proto_rawDescGZIP() []byte {
	file_fl_status_fl_status_proto_rawDescOnce.Do(func() {
		file_fl_status_fl_status_proto_rawDescData = protoimpl.X.CompressGZIP(file_fl_status_fl_status_proto_rawDescData)
	})
	return file_fl_status_fl_status_proto_rawDescData
}

var file_fl_status_fl_status_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_fl_status_fl_status_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_fl_status_fl_status_proto_goTypes = []interface{}{
	(Stages)(0),           // 0: Stages
	(*FLRoundStatus)(nil), // 1: FLRoundStatus
	(*Empty)(nil),         // 2: Empty
}
var file_fl_status_fl_status_proto_depIdxs = []int32{
	0, // 0: FLRoundStatus.stage:type_name -> Stages
	2, // 1: FlStatus.getRoundStatus:input_type -> Empty
	1, // 2: FlStatus.getRoundStatus:output_type -> FLRoundStatus
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_fl_status_fl_status_proto_init() }
func file_fl_status_fl_status_proto_init() {
	if File_fl_status_fl_status_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_fl_status_fl_status_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FLRoundStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fl_status_fl_status_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_fl_status_fl_status_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fl_status_fl_status_proto_goTypes,
		DependencyIndexes: file_fl_status_fl_status_proto_depIdxs,
		EnumInfos:         file_fl_status_fl_status_proto_enumTypes,
		MessageInfos:      file_fl_status_fl_status_proto_msgTypes,
	}.Build()
	File_fl_status_fl_status_proto = out.File
	file_fl_status_fl_status_proto_rawDesc = nil
	file_fl_status_fl_status_proto_goTypes = nil
	file_fl_status_fl_status_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// FlStatusClient is the client API for FlStatus service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FlStatusClient interface {
	GetRoundStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*FLRoundStatus, error)
}

type flStatusClient struct {
	cc grpc.ClientConnInterface
}

func NewFlStatusClient(cc grpc.ClientConnInterface) FlStatusClient {
	return &flStatusClient{cc}
}

func (c *flStatusClient) GetRoundStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*FLRoundStatus, error) {
	out := new(FLRoundStatus)
	err := c.cc.Invoke(ctx, "/FlStatus/getRoundStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FlStatusServer is the server API for FlStatus service.
type FlStatusServer interface {
	GetRoundStatus(context.Context, *Empty) (*FLRoundStatus, error)
}

// UnimplementedFlStatusServer can be embedded to have forward compatible implementations.
type UnimplementedFlStatusServer struct {
}

func (*UnimplementedFlStatusServer) GetRoundStatus(context.Context, *Empty) (*FLRoundStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoundStatus not implemented")
}

func RegisterFlStatusServer(s *grpc.Server, srv FlStatusServer) {
	s.RegisterService(&_FlStatus_serviceDesc, srv)
}

func _FlStatus_GetRoundStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlStatusServer).GetRoundStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FlStatus/GetRoundStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlStatusServer).GetRoundStatus(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _FlStatus_serviceDesc = grpc.ServiceDesc{
	ServiceName: "FlStatus",
	HandlerType: (*FlStatusServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getRoundStatus",
			Handler:    _FlStatus_GetRoundStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fl_status/fl_status.proto",
}
